spring:
  datasource:
    url: jdbc:mysql://cdb-jxfbh8rt.gz.tencentcdb.com:10092/inread_online?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: inread2019
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource