server:
  port: 8090
  use-forward-headers: true
spring:
  profiles:
    active: dev
  tomcat:
    uri-encoding: UTF-8
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

jwt:
  secret: inread19901123
  expiration: 604800000

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/in/read/*/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.in.read.*.entity
  global-config:
    db-config:
      db-type: mysql
      id-type: auto
      field-strategy: ignored
      column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    root: INFO
  file: logs/inread-web.log