server:
  port: 8090
spring:
  profiles:
    active: dev
  tomcat:
    uri-encoding: UTF-8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

jwt:
  secret: inread19901123
  expiration: 604800000