server:
  port: 8090
  use-forward-headers: true
spring:
  profiles:
    active: dev
  tomcat:
    uri-encoding: UTF-8
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

jwt:
  secret: inread19901123
  expiration: 604800000